apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: grupo-4-namespace
data:
  nginx.conf: |
    upstream admin {
        server clusterip-admin:8080;
    }
    upstream user {
        server clusterip-user:8081;
    }
    upstream order {
        server clusterip-order:8082;
    }
    server {
        proxy_set_header   Host            $http_host;
        proxy_set_header   Upgrade         $http_upgrade;
        proxy_set_header   X-Real-IP       $remote_addr;
        proxy_set_header   X-NginX-Proxy   true;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_connect_timeout 30s;
        proxy_read_timeout 30s;
        listen 80;

        rewrite ^/user/(.*) /user/$1;
        rewrite ^/order/(.*) /order/$1;
        rewrite ^/admin/(.*) /admin/$1;
        rewrite ^/(.*) /$1;

        location /user/ {
          proxy_pass http://user/;
        }
        location /admin/ {
          proxy_pass http://admin/;
        }
        location /order/ {
            proxy_pass http://order/;
        }
        location / {
            proxy_pass http://admin/;
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
          items:
            - key: nginx.conf
              path: default.conf